# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab4a90596cb4015ecd3c1dc135924f3b6ad9aea113f56a1e9cc882f7b72d09500ca536ad7441f485314e97d8b89dabb142c04a7277736dbca3b9d0a3945550d7

test:
  secret_key_base: 18881080cbe9c54c81f85f701c9675a44466245eb9a06511c8351e612acf01b427010381e97176b9b8a17e7fc7951fccf8d365e5fc9507284553ed15884bd379

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
